### PR TITLE
Read TLS key and cert files from tls.ini in auth_proxy

### LINKED ISSUE #1892: auth_proxy config
### Expected behavior
`auth_proxy` should use the `tls` plugin config for `key` and `cert` path. 

### Observed behavior
auth_proxy has hardcoded names (paths) for `key` and `cert`

**Current auth_proxy** (line 118 and 119)
```
var key = self.config.get('tls_key.pem', 'binary');
var cert = self.config.get('tls_cert.pem', 'binary');
```

### PR DESCRIPTION
**Pull request by amirkarimi**
Fixes #1892

### CODE REVIEW

File: plugins/auth/auth_proxy.js [hunk 1]
```diff
@@ -103,8 +113,8 @@ exports.try_auth_proxy = function (connection, hosts, user, passwd, cb) {
         response.push(rest);
         if (cont !== ' ') return;
 
-        let key;
-        let cert;
+        const key = self.config.get(self.tls_cfg.main.key || 'tls_key.pem', 'binary');
+        const cert = self.config.get(self.tls_cfg.main.cert || 'tls_cert.pem', 'binary');
```
Comment (msimerson) [inline plugins/auth/auth_proxy.js]: I'm kinda of torn on this change. The variable declarations need to be in this scope, but this change will load the (cached) TLS certificates, even if the next SMTP server never advertises `STARTTLS`. Is there some benefit to loading the certs up here?

Comment (amirkarimi) [reply plugins/auth/auth_proxy.js]: You're right I just wanted to prevent loading files several times in the loop. I'll return them back to the prev place as you mentioned they're cached. Right?

Comment (msimerson) [reply plugins/auth/auth_proxy.js]: Yep, the config loader caches the config files.

Comment (amirkarimi) [reply plugins/auth/auth_proxy.js]: Done
