### PR TITLE
fix(localhost-loop): fix outbound loop when target mx is localhost

### LINKED ISSUE #2809: Localhost mail loop problem
I am trying to solve kind of configuration problem - it is not Haraka issue per se

There are multiple servers which returns MX as 0.0.0.0 or 127.0.0.1, or other "problematic" IPs. What happens is that Haraka will deliver to itself and relay via outbound again. It depends on added headers but after ±100 deliveries Haraka will reject mail as looped mail. 

Thing is that malicious user can easily induce dos with this kind of behaviour. Only solution I've come up is kind of hacky with abusing metadata in headers. Am I missing something?

### PR DESCRIPTION
**Pull request by DoobleD**
Fixes #2809

Changes proposed in this pull request:
- keep target mx only if its IP is not a local IP

Checklist:
- [x] docs updated
- [ ] tests updated
- [x] [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md) updated

### CODE REVIEW

**Review by baudehlo — CHANGES_REQUESTED** [review]
I would wrap this in some sort of config too, something like cfg.local_mx_ok (which will disable this check, i.e. outbound to local IPs is disabled by default, as per this patch), and add it to booleans in outbound/config.js, and don't forget the docs.

**Comment by msimerson** [comment]
I'm not sure this is the right default. There are plenty of use cases where a MTA accepts mail and then delivers it to localhost on another port.

**Comment by baudehlo** [comment]
Sure but I guess my opinion is that, that is the rare scenario for people who know what they are doing. If we add a flag to it we have to pick a default and default safe seems best.

**Comment by DoobleD** [comment]
Thanks for the feedback. Here's an attempt at a config param as suggested.

File: outbound/config.js [hunk 1]
```diff
@@ -42,6 +42,9 @@ function load_config () {
     if (!cfg.received_header) {
         cfg.received_header = config.get('outbound.received_header') || 'Haraka outbound';
     }
+    if (!cfg.local_mx_ok) {
```
Comment (baudehlo) [inline outbound/config.js:45]: I think this needs added to `booleans` at the top too.

**Review by baudehlo — CHANGES_REQUESTED** [review]

File: outbound/config.js (hunk 1 above)
Comment (DoobleD) [reply outbound/config.js:46]: Thanks, fixed. :)

File: docs/Outbound.md [hunk 2]
```diff
@@ -95,6 +95,12 @@ Set this to `0` to completely disable the pooling code.
 This value determines how many concurrent connections can be made to a single
 IP address (destination) in the pool. Default: 10 connections.
 
+* `local_mx_ok`
+
+Default: false. By default, outbound to a local IP is disabled, to avoid creating 
+outbound loops. Set this to true if you want to allow outbound to local IPs. 
+This is be useful if you want to deliver mail to localhost on another port.
```
Comment (msimerson) [inline docs/Outbound.md:102]:
```suggestion
This could be useful if you want to deliver mail to localhost on another port.
```

**Review by msimerson — DISMISSED** [review]
LGTM

**Review by msimerson — APPROVED** [review]

File: outbound/mx_lookup.js [hunk 3]
```diff
@@ -33,8 +35,10 @@ exports.lookup_mx = function lookup_mx (domain, cb) {
         }
         else if (addresses && addresses.length) {
             for (let i=0,l=addresses.length; i < l; i++) {
-                const mx = wrap_mx(addresses[i]);
-                mxs.push(mx);
+                if (obc.cfg.local_mx_ok || !net_utils.is_local_ip(addresses[i].exchange)) {
```
Comment (analogic) [inline outbound/mx_lookup.js:38]: Sorry for being late to the party but addresses[i].exchange gives me hostname not IP

Comment (DoobleD) [reply outbound/mx_lookup.js:38]: Thanks for the feedback @analogic. 

I just tested it and you're right, I get the hostname too, whereas `net_utils.is_local_ip` seems to expect an ip. 

The change solves #2809 anyway because (from what I understand) the issue was addressing cases where the MX record was returning a local IP (not a hostname), such as with domain yeah.com:

```
$ dig MX yeah.com
...
yeah.com.		534	IN	MX	1000 0.0.0.0.
...
```

In that case `addresses = [ { exchange: '0.0.0.0', priority: 1000 } ]` and the fix does work.

The fix would fail for an MX record resolving to a local ip. Is this a legitimate use case? If yes, perhaps we could use `net_utils.get_ips_by_host` to resolve `addresses[i].exchange` to an ip? I'm wondering if this can badly impact performance though. I'm not knowledgeable enough on Haraka to evaluate this.

Comment (msimerson) [reply outbound/mx_lookup.js:38]: use `net.isIP` to define if .exchange is an IP or not. When its not an IP, using `net_utils.get_ips_by_host` to resolve should be fine.

Comment (DoobleD) [reply outbound/mx_lookup.js:38]: I've made two PRs as a fix attempts:
- https://github.com/haraka/Haraka/pull/3002
- https://github.com/haraka/haraka-net-utils/pull/63
