### PR TITLE
plugin: strip haraka-plugin- prefix from entries in plugin config

### LINKED ISSUE #2870: Regression in plugin name convention
### system info

Haraka.js — Version: 2.8.26
 --- | :---
Node | v14.15.0
OS | Linux
openssl | OpenSSL 1.1.1d  10 Sep 2019

### Expected behavior
Correctly load plugins and start up.

### Observed behavior
Crashes with
```
2020-12-04T08:51:33.078Z [CRIT] [-] [core] TypeError: Cannot read property 'timeout' of undefined
2020-12-04T08:51:33.078Z [CRIT] [-] [core]     at Object.plugins.run_next_hook (/mnt/c/Users/chris/repos/haraka-ep-outbound/node_modules/Haraka/plugins.js:522:35)
2020-12-04T08:51:33.079Z [CRIT] [-] [core]     at Object.plugins.run_hooks (/mnt/c/Users/chris/repos/haraka-ep-outbound/node_modules/Haraka/plugins.js:451:13)
2020-12-04T08:51:33.079Z [CRIT] [-] [core]     at Object.Server.createServer (/mnt/c/Users/chris/repos/haraka-ep-outbound/node_modules/Haraka/server.js:328:20)
2020-12-04T08:51:33.080Z [CRIT] [-] [core]     at Object.<anonymous> (/mnt/c/Users/chris/repos/haraka-ep-outbound/node_modules/Haraka/haraka.js:83:8)
2020-12-04T08:51:33.080Z [CRIT] [-] [core]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
2020-12-04T08:51:33.081Z [CRIT] [-] [core]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
2020-12-04T08:51:33.081Z [CRIT] [-] [core]     at Module.load (internal/modules/cjs/loader.js:928:32)
2020-12-04T08:51:33.081Z [CRIT] [-] [core]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2020-12-04T08:51:33.082Z [CRIT] [-] [core]     at Module.require (internal/modules/cjs/loader.js:952:19)
2020-12-04T08:51:33.082Z [CRIT] [-] [core]     at require (internal/modules/cjs/helpers.js:88:18)
2020-12-04T08:51:33.084Z [NOTICE] [-] [core] Shutting down
```

### Steps to reproduce
Configure plugins like so
```
helo.checks
tls
haraka-plugin-auth-imap
haraka-plugin-access-auth
clamd
haraka-plugin-known-senders
haraka-plugin-recipient-routes
data.headers
```
and run Haraka like so
`yarn run haraka -c .`

### PR DESCRIPTION
**Pull request by msimerson**
Fixes #2870
closes #2867
related to #2846

Changes proposed in this pull request:
- plugin: strip haraka-plugin- prefix from entries in plugin config

Checklist:
- [x] tests updated (n/a)
- [x] [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md) updated

### CODE REVIEW

File: plugins.js [hunk 1]
```diff
@@ -58,11 +58,8 @@ class Plugin {
         */
 
         plugin.hasPackageJson = false;
-        let name = plugin.name;
-        if (/^haraka-plugin-/.test(name)) {
-            name = name.replace(/^haraka-plugin-/, '');
-            plugin.name = name;
-        }
+        const name = ('haraka-plugin-' === plugin.name.substr(0,14)) ? plugin.name.substr(14) : plugin.name;
```
Comment (baudehlo) [inline plugins.js:61]:
```suggestion
        const name = plugin.name.startsWith('haraka-plugin-') ? plugin.name.substr(14) : plugin.name;
```

**Review by baudehlo — CHANGES_REQUESTED** [review]
