### PR TITLE
only apply default tls key/cert paths when undefined

### LINKED ISSUE #2108: tls plugin seems to ignore config
### system info

Haraka | Haraka.js — Version: 2.8.15
 --- | :---
Node | v6.10.3
OS | Linux 7cc78a8c8d99 4.9.36-moby #1 SMP Wed Jul 12 15:29:07 UTC 2017 x86_64 Linux
openssl | OpenSSL 1.0.2k  26 Jan 2017

### Expected behavior
Given the following, I expect the server to start without errors:

```
/ # haraka -i /server
create: /server
create: /server/plugins
create: /server/docs
create: /server/config
create: /server/config/smtp.ini
create: /server/config/log.ini
create: /server/config/plugins
create: /server/config/dkim
create: /server/config/dkim/dkim_key_gen.sh
/ # mkdir -p /server/config/foo
/ # cd /server/config/foo
/server/config/foo # openssl req -x509 -nodes -days 2190 -newkey rsa:2048 -keyout cert.pem -out key.pem
Generating a 2048 bit RSA private key
....+++
...............+++
writing new private key to 'cert.pem'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:.
State or Province Name (full name) [Some-State]:.
Locality Name (eg, city) []:
Organization Name (eg, company) [Internet Widgits Pty Ltd]:.
Organizational Unit Name (eg, section) []:
Common Name (e.g. server FQDN or YOUR name) []:example.com
Email Address []:
/server/config/foo # openssl dhparam -out dhparams.pem 1024
Generating DH parameters, 1024 bit long safe prime, generator 2
This is going to take a long time
...........................+..........................................................................................................................+...........................................................................................+........................+......................+............+.........+............................................................................+..............................................................................+..................................................................................................................................................................+.......................+...................................+..................+.......................+.............................+..............+..........................................................................................+.........................+......................................................................................................................................+........................................+................................................................+............+.........+........................+.................+..................+......+.............+...................+.................................................................................................................................................................................+..........................................+.....+...+.....................+......+...+...+.......................................................................................................................++*++*++*
/server/config/foo # ls -l
total 12
-rw-r--r--    1 root     root          1704 Sep 13 19:31 cert.pem
-rw-r--r--    1 root     root           245 Sep 13 19:34 dhparams.pem
-rw-r--r--    1 root     root          1099 Sep 13 19:31 key.pem
/server/config/foo # cd ..
/server/config # grep tls plugins
# see 'haraka -h tls' for config instructions before enabling!
tls
/server/config # cat tls.ini
key=foo/key.pem
cert=foo/cert.pem
dhparam=foo/dhparam.pem
```

### Observed behavior

However,

```
/server/config # haraka -c /server
Returning boolean false for main.timestamps=false
loaded TLD files: 1=1544 2=6156 3=2246
loaded 8357 Public Suffixes
Returning boolean true for main.reject=true
Returning boolean false for main.allow_mx_ip=0
Returning boolean true for main.reject_no_mx=1
loglevel: INFO
log format: DEFAULT
Starting up Haraka version 2.8.15
[INFO] [-] [core] Loading plugins
[INFO] [-] [core] Loading plugin: access
[INFO] [-] [access] skipping helo.checks.regexps
[INFO] [-] [core] Loading plugin: dnsbl
[INFO] [-] [core] Loading plugin: helo.checks
[INFO] [-] [core] Loading plugin: tls
[INFO] [-] [core] loading tls.ini
[ERROR] [-] [core] tls key tls_key.pem could not be loaded.
[ERROR] [-] [core] Config {
  root_path: '/server/config',
  module_config: [Function],
  overrides_path: '/server/config' }
[ERROR] [-] [core] tls cert tls_cert.pem could not be loaded.
[INFO] [-] [core] Loading plugin: mail_from.is_resolvable
[INFO] [-] [core] Loading plugin: rcpt_to.in_host_list
[INFO] [-] [core] Loading plugin: data.headers
[INFO] [-] [core] Loading plugin: queue/smtp_forward
[INFO] [-] [core] Loading plugin: max_unrecognized_commands
[NOTICE] [-] [core] Listening on :::25
[INFO] [-] [core] [outbound] Loading outbound queue from /server/queue
[WARN] [-] [dnsbl] zone 'zen.spamhaus.org' did not respond to test point (null)
[WARN] [-] [dnsbl] disabling zone 'zen.spamhaus.org'
```

### PR DESCRIPTION
**Pull request by msimerson**
Fixes #2108

Changes proposed in this pull request:
- only apply default tls key/cert paths when undefined in tls.ini
- permit dhparams.pem file to be in a directory
- [x] [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md) updated

### CODE REVIEW

**Comment by msimerson** [comment]
@alkar, care to test this and verify it solves the problem?

File: tls_socket.js [hunk 1]
```diff
@@ -506,11 +508,12 @@ exports.ensureDhparams = function (done) {
...
     }
 
-    let filePath = tlss.cfg.main.dhparam;
-    if (!filePath) filePath = path.resolve(exports.config.root_path, 'dhparams.pem');
-    log.loginfo(`Generating a 2048 bit dhparams file at ${filePath}`);
+    const filePath = tlss.cfg.main.dhparam || 'dhparams.pem';
+    const fpResolved = path.resolve(exports.config.root_path, filePath);
 
-    const o = spawn('openssl', ['dhparam', '-out', `${filePath}`, '2048']);
+    log.loginfo(`Generating a 2048 bit dhparams file at ${fpResolved}`);
```
Comment (Dexus) [inline tls_socket.js]: Should be "Generating a 1024..." below you generate only a 1024 key...

File: tls_socket.js [hunk 2]
```diff
@@ -506,11 +508,12 @@ exports.ensureDhparams = function (done) {
...
+
+    const o = spawn('openssl', ['dhparam', '-out', `${fpResolved}`, '1024']);
```
Comment (Dexus) [inline tls_socket.js]: here you only generate a 1024 key... not a 2048 as in the log above.

**Comment by alkar** [comment]
@msimerson tested and it doesn't give errors anymore. However, I just realised that it doesn't advertise `STARTTLS`. Possibly a separate issue or misconfiguration but I can't claim I properly tested this without actually making a TLS connection.

These are from a server using the keys from their default locations:

```
/ # openssl s_client -connect something.com:25 -starttls smtp
CONNECTED(00000003)
didn't found starttls in server response, try anyway...
140533219769228:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:794:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 211 bytes and written 342 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1505382736
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
```

```
/ # nc something.com 25
220 haraka.test ESMTP Haraka 2.8.15 ready
EHLO another.com
250-haraka.test Hello Unknown [172.17.0.2], Haraka is at your service.
250-PIPELINING
250-8BITMIME
250-SMTPUTF8
250 SIZE 26214400
/ #
```

File: tls_socket.js (hunk 1 above)
Comment (msimerson) [reply tls_socket.js]: Good catch, I dropped that to sped it up during testing, I'll switch it back.

**Comment by msimerson** [comment]
I'm not able to replicate your issue when this change is applied. I've tested two ways, in a clean VM and in a local checkout of this branch:

## VM deployment test

````
# npm install msimerson/Haraka/#2108-tls-files-in-dir
# cd /data/haraka/config
# ls *.pem
ls: *.pem: No such file or directory
[root@vmware /data/haraka/config]# ls foo/
dhparams.pem	tls_cert.pem	tls_key.pem
[root@vmware /data/haraka/config]# cat tls.ini 
key=foo/tls_key.pem
cert=foo/tls_cert.pem
dhparam=foo/dhparams.pem

[root@vmware /data/haraka/config]# openssl s_client -connect haraka:25 -starttls smtp
CONNECTED(00000003)
depth=0 C = US, ST = Washington, L = Seattle, O = Mail Toaster, CN = vmware.imac27.simerson.net
verify error:num=18:self signed certificate
verify return:1
depth=0 C = US, ST = Washington, L = Seattle, O = Mail Toaster, CN = vmware.imac27.simerson.net
verify return:1
---
Certificate chain
 0 s:/C=US/ST=Washington/L=Seattle/O=Mail Toaster/CN=vmware.imac27.simerson.net
   i:/C=US/ST=Washington/L=Seattle/O=Mail Toaster/CN=vmware.imac27.simerson.net
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDszCCApugAwIBAgIJAJffd9m2/5NbMA0GCSqGSIb3DQEBCwUAMHAxCzAJBgNV
BAYTAlVTMRMwEQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMRUw
EwYDVQQKDAxNYWlsIFRvYXN0ZXIxIzAhBgNVBAMMGnZtd2FyZS5pbWFjMjcuc2lt
ZXJzb24ubmV0MB4XDTE3MDgzMDIzMjg1M1oXDTIzMDgyOTIzMjg1M1owcDELMAkG
A1UEBhMCVVMxEzARBgNVBAgMCldhc2hpbmd0b24xEDAOBgNVBAcMB1NlYXR0bGUx
FTATBgNVBAoMDE1haWwgVG9hc3RlcjEjMCEGA1UEAwwadm13YXJlLmltYWMyNy5z
aW1lcnNvbi5uZXQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDNdIKG
RrJpx+EdrV9ol26i2YnA1Fm4lmAIVV0G6ViwOfV0fUxwiOWfjg3q7if72AQYHvzX
JdJDglvLBb5UlWpXm3KvIY1w09XBmwxdAOtbcNb58TQBBYnWiKY7popcwWg+6VTx
M0xfx1F+VZ+qR0zhv1C4iq+6C6u53bC2dGi6hmSukbvTwyPTydcD3NhSy5Qatr/M
wAIcXdc3fIw2qY4dZwGllakofysuLgG6/qt1sFGLoi006u1pOPQvxyPca5mm5sfu
LWPt0c5lkDu+SWUP4NxR0BBw7yz3iYmSNJXIzbO0vz9s1cMLBnfW8JrsZBRca825
EOd2RFR2NAzjR5fTAgMBAAGjUDBOMB0GA1UdDgQWBBTq1TDOdDzJLyScuc6UtvEb
zdEfgTAfBgNVHSMEGDAWgBTq1TDOdDzJLyScuc6UtvEbzdEfgTAMBgNVHRMEBTAD
AQH/MA0GCSqGSIb3DQEBCwUAA4IBAQC7IPH70S/KWW4e/m+LJYNHzA6BJ+z/BVmO
48WahtGhGk7cTL99kloxR2CqKREDnmlXd+9zS4CO/YZrXA0V9x4AJgW5/0zb8UF8
4yNRtTqxzE40+66L8SEFNytdQDTUNw9IesJKxcYsaYy3tyDzd8tuo01uDHtBL9Sy
FGRZNMIitbx/iq9We7+5UFuhLferTRHs5BJzk9Aj6JtQkNZLnRLuCX9LFAm98GqT
/tRzaqJNjgJzgMkoFnSstzqGcgAp1IETmQW3Hvqjtm7fibiPWWSP9KU/bdupnSrL
IyTIQtKRrXs1uD9jc2GnympM+O68bi0aZFIzwlfPgReS+LG2pIsm
-----END CERTIFICATE-----
subject=/C=US/ST=Washington/L=Seattle/O=Mail Toaster/CN=vmware.imac27.simerson.net
issuer=/C=US/ST=Washington/L=Seattle/O=Mail Toaster/CN=vmware.imac27.simerson.net
---
No client certificate CA names sent
Client Certificate Types: RSA sign, DSA sign, ECDSA sign
Requested Signature Algorithms: RSA+SHA512:DSA+SHA512:ECDSA+SHA512:RSA+SHA384:DSA+SHA384:ECDSA+SHA384:RSA+SHA256:DSA+SHA256:ECDSA+SHA256:RSA+SHA224:DSA+SHA224:ECDSA+SHA224:RSA+SHA1:DSA+SHA1:ECDSA+SHA1
Shared Requested Signature Algorithms: RSA+SHA512:DSA+SHA512:ECDSA+SHA512:RSA+SHA384:DSA+SHA384:ECDSA+SHA384:RSA+SHA256:DSA+SHA256:ECDSA+SHA256:RSA+SHA224:DSA+SHA224:ECDSA+SHA224:RSA+SHA1:DSA+SHA1:ECDSA+SHA1
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 1842 bytes and written 480 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: 6FDCECF6BEF4420DC42FF1296BA823CACD48202AC95DECC898F9C4DD071B4DE9
    Session-ID-ctx: 
    Master-Key: C1B2726401374C8EBE9A25A59A13F92DFAA86E48E9A754FA4FF041E1E9337F989B5E57F94F5E413DF7C0061A0A4FD353
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - 94 99 5b 90 5f b7 ba f0-8b 36 41 d3 e9 d3 4c 59   ..[._....6A...LY
    0010 - 21 ab 4d 0d cd 84 85 c2-f6 9a aa 2d b2 e2 79 32   !.M........-..y2
    0020 - 14 09 d9 2e 0e 3d 67 ed-e5 eb 2a 19 9c 92 70 89   .....=g...*...p.
    0030 - 5f a9 27 b2 97 28 7c 20-82 0b dc 85 9c 5e 31 c4   _.'..(| .....^1.
    0040 - 65 af 10 cb 22 89 4c 02-49 fb a1 83 39 cb 59 1f   e...".L.I...9.Y.
    0050 - 73 52 0d 60 e4 60 b8 63-93 f6 ff f9 39 1f c5 99   sR.`.`.c....9...
    0060 - 6f 8d 53 5e b7 ce 83 46-d4 bf 2c d9 4b 3e 11 04   o.S^...F..,.K>..
    0070 - 93 80 5d 41 3e 13 c8 02-f3 2d ca 5a c1 1d 90 17   ..]A>....-.Z....
    0080 - 9a 66 19 94 e7 9c 11 c8-83 97 60 53 48 68 3c 8a   .f........`SHh<.
    0090 - b6 b7 f5 f4 88 7b 35 f6-80 1b 77 a9 1b 49 12 8c   .....{5...w..I..

    Start Time: 1505358464
    Timeout   : 300 (sec)
    Verify return code: 18 (self signed certificate)
---
250 STARTTLS
quit
221 haraka closing connection. Have a jolly good day.
closed
````

### Local git checkout

````
[matt@imac27] ~/git/haraka $ git branch
* 2108-tls-files-in-dir

[matt@imac27] ~/git/haraka $ ./bin/haraka -i tls-test
create: /Users/matt/git/haraka/tls-test
create: /Users/matt/git/haraka/tls-test/plugins
create: /Users/matt/git/haraka/tls-test/docs
create: /Users/matt/git/haraka/tls-test/config
create: /Users/matt/git/haraka/tls-test/config/smtp.ini
create: /Users/matt/git/haraka/tls-test/config/log.ini
create: /Users/matt/git/haraka/tls-test/config/plugins
create: /Users/matt/git/haraka/tls-test/config/dkim
create: /Users/matt/git/haraka/tls-test/config/dkim/dkim_key_gen.sh

[matt@imac27] ~/git/haraka $ mkdir tls-test/config/bar

[matt@imac27] ~/git/haraka $ openssl req -x509 -nodes -days 2190 -newkey rsa:2048 -keyout tls-test/config/bar/tls_key.pem -out tls-test/config/bar/tls_cert.pem
Generating a 2048 bit RSA private key
.....+++
...................................................................................................+++
writing new private key to 'tls-test/config/bar/tls_key.pem'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:
State or Province Name (full name) [Some-State]:
Locality Name (eg, city) []:
Organization Name (eg, company) [Internet Widgits Pty Ltd]:
Organizational Unit Name (eg, section) []:
Common Name (e.g. server FQDN or YOUR name) []:
Email Address []:

[matt@imac27] ~/git/haraka $ tee tls-test/config/tls.ini <<EO_TLS
> key=bar/tls_key.pem
> cert=bar/tls_cert.pem
> EO_TLS
key=bar/tls_key.pem
cert=bar/tls_cert.pem

[matt@imac27] ~/git/haraka $ sed -i '' -e '/^# tls/ s/# //' tls-test/config/plugins

[matt@imac27] ~/git/haraka $ sudo ./bin/haraka -c tls-test

[matt@imac27] ~/git/haraka $ sudo ./bin/haraka -c tls-test
Returning boolean false for main.timestamps=false
loaded TLD files: 1=1534 2=6132 3=2170
loaded 8229 Public Suffixes
Returning boolean true for main.reject=true
Returning boolean false for main.allow_mx_ip=0
Returning boolean true for main.reject_no_mx=1
loglevel: INFO
log format: DEFAULT
Starting up Haraka version 2.8.15
[INFO] [-] [core] Loading plugins
[INFO] [-] [core] Loading plugin: access
[INFO] [-] [access] skipping helo.checks.regexps
[INFO] [-] [core] Loading plugin: dnsbl
[INFO] [-] [core] Loading plugin: helo.checks
[INFO] [-] [core] Loading plugin: tls
[INFO] [-] [core] loading tls.ini
[INFO] [-] [core] Generating a 2048 bit dhparams file at /Users/matt/git/haraka/tls-test/config/dhparams.pem
[INFO] [-] [core] Loading plugin: mail_from.is_resolvable
[INFO] [-] [core] Loading plugin: rcpt_to.in_host_list
[INFO] [-] [core] Loading plugin: data.headers
[INFO] [-] [core] Loading plugin: queue/smtp_forward
[INFO] [-] [core] Loading plugin: max_unrecognized_commands
[NOTICE] [-] [core] Listening on :::25
[INFO] [-] [core] [outbound] Loading outbound queue from /Users/matt/git/haraka/tls-test/queue
^Z
[1]+  Stopped                 sudo ./bin/haraka -c tls-test
[matt@imac27] ~/git/haraka $ bg
[1]+ sudo ./bin/haraka -c tls-test &

[matt@imac27] ~/git/haraka $ openssl s_client -connect localhost:25 -starttls smtp
CONNECTED(00000003)
[NOTICE] [99E96D1F-B7A3-4A00-99D2-E40BE5635700] [core] connect ip=127.0.0.1 port=64363 local_ip=:: local_port=25
[INFO] [99E96D1F-B7A3-4A00-99D2-E40BE5635700] [helo.checks] multi: true, skip:proto_mismatch(private), host_mismatch(private)
depth=0 C = AU, ST = Some-State, O = Internet Widgits Pty Ltd
verify error:num=18:self signed certificate
verify return:1
depth=0 C = AU, ST = Some-State, O = Internet Widgits Pty Ltd
verify return:1
[INFO] [99E96D1F-B7A3-4A00-99D2-E40BE5635700] [tls] secured: cipher=ECDHE-RSA-AES128-GCM-SHA256 version=TLSv1/SSLv3 verified=false
[INFO] [99E96D1F-B7A3-4A00-99D2-E40BE5635700] [core]  hook=unrecognized_command plugin=tls function=upgrade_connection params=STARTTLS retval=OK msg=""
---
Certificate chain
 0 s:/C=AU/ST=Some-State/O=Internet Widgits Pty Ltd
   i:/C=AU/ST=Some-State/O=Internet Widgits Pty Ltd
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDXTCCAkWgAwIBAgIJAO9N5wRy73mAMA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNV
BAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBX
aWRnaXRzIFB0eSBMdGQwHhcNMTcwOTE0MTc1NTQ5WhcNMjMwOTEzMTc1NTQ5WjBF
MQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50
ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
CgKCAQEA7YJihuv+G/IL22W2yi9v9bwVKvMhf8cWmBvZY3m9Zmfx0818eJ2YlcNG
RTVjQ42pWPrHhM36iqYhcfoZsgw+Gf74xxutYbJdfHcJLA8flELrlmWuIAPpway6
44B5WHe6eM/B45MWUBfQLvHq80j790bJXjblgjkxmxl3aMO5v45JSM3iHReRtaPs
loJyZn/ZqACRFP8SOcfyDtzBOdK3nW9WXvmV4Vj5eI3KtBruxHC+BQ0iNb/oNSF4
bdpVFTv+JnSnR7os7suBvtRJuDD4cISHZBsyfSev8FMjVdUvGRJ3ICvVshoel6aA
pijdWpqgo8Zhba2u1zo/mltLhjNBOwIDAQABo1AwTjAdBgNVHQ4EFgQUOPHGTJyr
G6Rfgl7+HFVAaSzE3aYwHwYDVR0jBBgwFoAUOPHGTJyrG6Rfgl7+HFVAaSzE3aYw
DAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEADCPsk0sJi2CQb9vC/x7z
5stndwWxISgJDLadOtnkkhN+BqDUX1mntIB9kqQ7SS+WJJDzuJO1y5bK/1TefAQq
mOA2RmH6JwZiuC7dwemfksvx/ORdfzw7g6wUq71pGOEzsTWEu3wwt4iVj1sDoMVw
FUY5vEhMUMDinncwON6mW1fKKXTglV1RY7tV+jVd0Fqn4XuckNoHMg8Of7/aiBIs
hTMzI23kL+z411YmjhF0+qKy+vO6GTif9wK1CdQL61bYdNtRJZW730YBWJ5YYKI7
xM6CfbU7sP2pEO0TJaFp9uA4YIuu9HYvtTvcJQHKgDPwKZ+SeYALtT5/Ey2PiAig
Vg==
-----END CERTIFICATE-----
subject=/C=AU/ST=Some-State/O=Internet Widgits Pty Ltd
issuer=/C=AU/ST=Some-State/O=Internet Widgits Pty Ltd
---
No client certificate CA names sent
Client Certificate Types: RSA sign, DSA sign, ECDSA sign
Requested Signature Algorithms: RSA+SHA512:DSA+SHA512:ECDSA+SHA512:RSA+SHA384:DSA+SHA384:ECDSA+SHA384:RSA+SHA256:DSA+SHA256:ECDSA+SHA256:RSA+SHA224:DSA+SHA224:ECDSA+SHA224:RSA+SHA1:DSA+SHA1:ECDSA+SHA1
Shared Requested Signature Algorithms: RSA+SHA512:DSA+SHA512:ECDSA+SHA512:RSA+SHA384:DSA+SHA384:ECDSA+SHA384:RSA+SHA256:DSA+SHA256:ECDSA+SHA256:RSA+SHA224:DSA+SHA224:ECDSA+SHA224:RSA+SHA1:DSA+SHA1:ECDSA+SHA1
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 1787 bytes and written 481 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: 6BB769157B3C08037DCA5FDD597FCA87BF0F06237BC9BAAF557D9E5ADA884C33
    Session-ID-ctx: 
    Master-Key: 54487A545CF0EDFEF475F046A8BBBFD818B2D5268AFC42FCCB50BA98FF0AB9C46A8F7B8E0B061B4BAFDD8ECAC5FF7774
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - 36 6a 64 2a 52 c1 00 9b-4b 62 96 b0 7e f0 ec 94   6jd*R...Kb..~...
    0010 - d0 76 27 12 91 ec 54 3c-47 fe 76 9a 38 56 86 c8   .v'...T<G.v.8V..
    0020 - 16 05 8c f7 04 60 5c d1-a9 28 35 fd 1a 16 cd 3b   .....`\..(5....;
    0030 - e3 a7 23 02 76 97 ee f2-2b ac d1 d2 dd ba e7 9e   ..#.v...+.......
    0040 - 4a 55 fe 73 70 8d 29 3d-18 69 68 da 66 3a df 72   JU.sp.)=.ih.f:.r
    0050 - 01 53 7d 66 75 9d 9f 8c-b7 4b 6e 8b 24 b3 db d8   .S}fu....Kn.$...
    0060 - 7d 19 b6 14 9f b4 3e 18-11 b1 f0 01 e5 2d 9e d7   }.....>......-..
    0070 - ce 6b 6d 63 d6 1e c1 6d-b7 66 ef 3e 48 57 a9 30   .kmc...m.f.>HW.0
    0080 - f9 4d d3 fd 51 99 2e 8f-2f ef 2c 84 a7 30 33 56   .M..Q.../.,..03V
    0090 - 7c 06 bc 36 3b 64 80 5d-d1 89 ed 30 cf f2 40 e3   |..6;d.]...0..@.

    Start Time: 1505412048
    Timeout   : 300 (sec)
    Verify return code: 18 (self signed certificate)
---
250 STARTTLS
quit
221 imac27.simerson.net closing connection. Have a jolly good day.
[NOTICE] [99E96D1F-B7A3-4A00-99D2-E40BE5635700] [core] disconnect ip=127.0.0.1 rdns=localhost helo="" relay=N early=N esmtp=Y tls=Y pipe=N errors=0 txns=0 rcpts=0/0/0 msgs=0/0/0 bytes=0 lr="" time=5.051
closed

**Comment by smfreegard** [comment]
@msimerson - you've tested differently to @alkar - in his testing he did not place the certificates in a sub-directory but just put them in `config` and deleted `tls.ini`.

**Comment by msimerson** [comment]
> @msimerson - you've tested differently to @alkar -

That depends on *which* of his tests your referring to. I was testing based on his description in #2108, but it works just as well with no TLS config:

````
[matt@imac27] ~/git/haraka $ ./bin/haraka -i tls-test
create: /Users/matt/git/haraka/tls-test
create: /Users/matt/git/haraka/tls-test/plugins
create: /Users/matt/git/haraka/tls-test/docs
create: /Users/matt/git/haraka/tls-test/config
create: /Users/matt/git/haraka/tls-test/config/smtp.ini
create: /Users/matt/git/haraka/tls-test/config/log.ini
create: /Users/matt/git/haraka/tls-test/config/plugins
create: /Users/matt/git/haraka/tls-test/config/dkim
create: /Users/matt/git/haraka/tls-test/config/dkim/dkim_key_gen.sh

[matt@imac27] ~/git/haraka $ sed -i '' -e '/^# tls/ s/# //' tls-test/config/plugins

[matt@imac27] ~/git/haraka $ sudo ./bin/haraka -c tls-test
Returning boolean false for main.timestamps=false
loaded TLD files: 1=1534 2=6132 3=2170
loaded 8229 Public Suffixes
Returning boolean true for main.reject=true
Returning boolean false for main.allow_mx_ip=0
Returning boolean true for main.reject_no_mx=1
loglevel: INFO
log format: DEFAULT
Starting up Haraka version 2.8.15
[INFO] [-] [core] Loading plugins
[INFO] [-] [core] Loading plugin: access
[INFO] [-] [access] skipping helo.checks.regexps
[INFO] [-] [core] Loading plugin: dnsbl
[INFO] [-] [core] Loading plugin: helo.checks
[INFO] [-] [core] Loading plugin: tls
[INFO] [-] [core] loading tls.ini
[ERROR] [-] [core] tls key tls_key.pem could not be loaded.
[ERROR] [-] [core] Config {
  root_path: '/Users/matt/git/haraka/tls-test/config',
  module_config: [Function],
  overrides_path: '/Users/matt/git/haraka/tls-test/config' }
[ERROR] [-] [core] tls cert tls_cert.pem could not be loaded.
[INFO] [-] [core] Loading plugin: mail_from.is_resolvable
[INFO] [-] [core] Loading plugin: rcpt_to.in_host_list
[INFO] [-] [core] Loading plugin: data.headers
[INFO] [-] [core] Loading plugin: queue/smtp_forward
[INFO] [-] [core] Loading plugin: max_unrecognized_commands
[NOTICE] [-] [core] Listening on :::25
[INFO] [-] [core] [outbound] Loading outbound queue from /Users/matt/git/haraka/tls-test/queue
^C[NOTICE] [-] [core] SIGINT received
[INFO] [-] [core] Shutting down.

[matt@imac27] ~/git/haraka $ openssl req -x509 -nodes -days 2190 -newkey rsa:2048 -keyout tls-test/config/tls_key.pem -out tls-test/config/tls_cert.pem
Generating a 2048 bit RSA private key
....................................................+++
..+++
writing new private key to 'tls-test/config/tls_key.pem'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:
State or Province Name (full name) [Some-State]:
Locality Name (eg, city) []:
Organization Name (eg, company) [Internet Widgits Pty Ltd]:
Organizational Unit Name (eg, section) []:
Common Name (e.g. server FQDN or YOUR name) []:
Email Address []:
[matt@imac27] ~/git/haraka $ 
[matt@imac27] ~/git/haraka $ sudo ./bin/haraka -c tls-test
Returning boolean false for main.timestamps=false
loaded TLD files: 1=1534 2=6132 3=2170
loaded 8229 Public Suffixes
Returning boolean true for main.reject=true
Returning boolean false for main.allow_mx_ip=0
Returning boolean true for main.reject_no_mx=1
loglevel: INFO
log format: DEFAULT
Starting up Haraka version 2.8.15
[INFO] [-] [core] Loading plugins
[INFO] [-] [core] Loading plugin: access
[INFO] [-] [access] skipping helo.checks.regexps
[INFO] [-] [core] Loading plugin: dnsbl
[INFO] [-] [core] Loading plugin: helo.checks
[INFO] [-] [core] Loading plugin: tls
[INFO] [-] [core] loading tls.ini
[INFO] [-] [core] Generating a 2048 bit dhparams file at /Users/matt/git/haraka/tls-test/config/dhparams.pem
[INFO] [-] [core] Loading plugin: mail_from.is_resolvable
[INFO] [-] [core] Loading plugin: rcpt_to.in_host_list
[INFO] [-] [core] Loading plugin: data.headers
[INFO] [-] [core] Loading plugin: queue/smtp_forward
[INFO] [-] [core] Loading plugin: max_unrecognized_commands
[NOTICE] [-] [core] Listening on :::25
[INFO] [-] [core] [outbound] Loading outbound queue from /Users/matt/git/haraka/tls-test/queue
[INFO] [-] [core] Saved to /Users/matt/git/haraka/tls-test/config/dhparams.pem
[NOTICE] [ACFE0149-BB5C-4964-BFA6-77BD252DFA14] [core] connect ip=127.0.0.1 port=64486 local_ip=:: local_port=25
[INFO] [ACFE0149-BB5C-4964-BFA6-77BD252DFA14] [helo.checks] multi: true, skip:proto_mismatch(private), host_mismatch(private)
[INFO] [ACFE0149-BB5C-4964-BFA6-77BD252DFA14] [tls] secured: cipher=ECDHE-RSA-AES128-GCM-SHA256 version=TLSv1/SSLv3 verified=false
[INFO] [ACFE0149-BB5C-4964-BFA6-77BD252DFA14] [core]  hook=unrecognized_command plugin=tls function=upgrade_connection params=STARTTLS retval=OK msg=""
[NOTICE] [ACFE0149-BB5C-4964-BFA6-77BD252DFA14] [core] disconnect ip=127.0.0.1 rdns=localhost helo="" relay=N early=N esmtp=Y tls=Y pipe=N errors=0 txns=0 rcpts=0/0/0 msgs=0/0/0 bytes=0 lr="" time=19.328
````

**Comment by smfreegard** [comment]
> That depends on which of his tests you're referring to. I was testing based on his description in #2108, but it works just as well with no TLS config:

Ok - I was just pointing out that I noticed there was a difference and that might be significant.

**Comment by msimerson** [comment]
There may be an additional problem (not yet identified) but this definitely fixes #2108. If another issue arises, I'll fix it in a new PR.

**Comment by gramakri** [comment]
@alkar @msimerson @smfreegard Phew, after much debugging, I have found the root cause of the problem in https://github.com/haraka/Haraka/pull/2111#issuecomment-329433771. We get the same errors on the Cloudron mail server after updating to 2.8.16. The issue is to do with the node version. Cloudron was running Haraka with version 6.9.5. The original bug report says that Haraka was run with 6.10.3. https://github.com/haraka/Haraka/issues/2108#issue-257498164. Running Haraka with the 6.11.3. LTS fixes the issue. So, this is clearly a user/packaging error since package.json expliclty says `>= 6.11.3`.

Leaving this node so other people can find it. Do you have any insight as to what has changed between these node versions?

**Comment by msimerson** [comment]
> Do you have any insight as to what has changed between these node versions?

Not exactly, **but** the main reason we keep bumping the min version in package.json to the latest LTS release is because of security (primarily: TLS) updates that effect node. These usually involve disabling insecure ciphers and such. To get more specific you'll have to go spelunking [in the 6.x Changes](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md).
