### PR TITLE
Advanced pool

### LINKED ISSUE #1576: Crash: release called twice for the same resource
### Haraka version
 2.8.8

### Observed behavior
```
[ERROR] [806DE749-F0A2-4BA7-9F4D-74FCEDCBAE99.1.1] [outbound] Ongoing connection failed to cli.ent.ip.addr:25 : Error: write after end
[INFO] [-] [core] [outbound] [outbound::25:cli.ent.ip.addr:undefined:50] dispense() clients=0 available=1
[INFO] [806DE749-F0A2-4BA7-9F4D-74FCEDCBAE99.1.1] [outbound] Temp failing 1472505160080_1_5187_8878.relay for 128 seconds: Tried all MXs
[NOTICE] [806DE749-F0A2-4BA7-9F4D-74FCEDCBAE99.1.1] [outbound] delivered file=1472505160080_1_5187_8878.relay domain="--redacted--.com" host="staff.--redacted--.com" ip=cli.ent.ip.addr port=25 mode=SMTP tls=N auth=N response="" delay=7230.286 fails=2 rcpts=1/0/0
[ERROR] [-] [core] [outbound] [outbound::25:cli.ent.ip.addr:undefined:50] release called twice for the same resource: Error
    at Pool.release (/usr/lib/node_modules/Haraka/node_modules/generic-pool/lib/generic-pool.js:409:65)
    at release_client (/usr/lib/node_modules/Haraka/outbound.js:1228:10)
    at finish_processing_mail (/usr/lib/node_modules/Haraka/outbound.js:1477:9)
    at pluggableStream.<anonymous> (/usr/lib/node_modules/Haraka/outbound.js:1709:25)
    at emitOne (events.js:77:13)
    at pluggableStream.emit (events.js:169:7)
    at pluggableStream.socket.process_data (/usr/lib/node_modules/Haraka/line_socket.js:23:20)
    at pluggableStream.<anonymous> (/usr/lib/node_modules/Haraka/line_socket.js:34:48)
    at emitOne (events.js:77:13)
    at pluggableStream.emit (events.js:169:7)
[WARN] [-] [core] [outbound] Socket [outbound::25:cli.ent.ip.addr:undefined:50] in pool got FIN
[INFO] [-] [core] [outbound] [outbound::25:cli.ent.ip.addr:undefined:50] force destroying all objects
[CRIT] [-] [core] Error: Callback was already called.
[CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/node_modules/async/lib/async.js:43:36
[CRIT] [-] [core]     at HMailItem.hmail.next_cb (/usr/lib/node_modules/Haraka/outbound.js:98:9)
[CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/outbound.js:2131:15
[CRIT] [-] [core]     at FSReqWrap.oncomplete (fs.js:82:15)
[NOTICE] [-] [core] Shutting down
root@relay:#
```

### PR DESCRIPTION
**Pull request by baudehlo**
Fixes #1576 and possibly others

Changes proposed in this pull request:
- Mostly belt and braces around the pool code
- There still appears to be an issue with the pool getting locked up, but I'll continue working on that in another branch

Checklist:
- [ ] docs updated
- [ ] tests updated

### CODE REVIEW

File: outbound.js [hunk 1]
```diff
@@ -1492,7 +1514,12 @@ HMailItem.prototype.try_deliver_host_on_socket = function (mx, host, port, socke
         return send_command('MAIL', 'FROM:' + self.todo.mail_from);
     };
 
+    var fp_called = false;
```
Comment (msimerson) [inline outbound.js]: I worry about this value getting toggled to true and then remaining true forever. Does outbound spawn and destroy instances, or run and run and run?

Comment (baudehlo) [inline outbound.js]: It's to ensure that `finish_processing_mail` doesn't get called twice. It's standard practise to use a closure like this.
