### PR TITLE
Catch errors on header decode in rfc2231

### LINKED ISSUE #1596: Haraka outgoing explodes with URIError: URI malformed
### Haraka version
2.8.8

### Expected behavior
Send the email out.

### Observed behavior
``` js
2016-09-14T09:37:08.606Z [CRIT] [-] [core] URIError: URI malformed
2016-09-14T09:37:08.606Z [CRIT] [-] [core]     at decodeURIComponent (native)
2016-09-14T09:37:08.606Z [CRIT] [-] [core]     at /home/michael/Documents/Projects/migadu_mail/haraka-outgoing/node_modules/Haraka/mailheader.js:145:17
2016-09-14T09:37:08.606Z [CRIT] [-] [core]     at RegExp.[Symbol.replace] (native)
2016-09-14T09:37:08.607Z [CRIT] [-] [core]     at RegExp.[Symbol.replace] (native)
2016-09-14T09:37:08.607Z [CRIT] [-] [core]     at String.replace (native)
2016-09-14T09:37:08.607Z [CRIT] [-] [core]     at Header.decode_header (/home/michael/Documents/Projects/migadu_mail/haraka-outgoing/node_modules/Haraka/mailheader.js:160:15)
2016-09-14T09:37:08.607Z [CRIT] [-] [core]     at Header._add_header_decode (/home/michael/Documents/Projects/migadu_mail/haraka-outgoing/node_modules/Haraka/mailheader.js:232:20)
2016-09-14T09:37:08.607Z [CRIT] [-] [core]     at /home/michael/Documents/Projects/migadu_mail/haraka-outgoing/node_modules/Haraka/mailheader.js:53:18
2016-09-14T09:37:08.607Z [CRIT] [-] [core]     at Array.forEach (native)
2016-09-14T09:37:08.607Z [CRIT] [-] [core]     at /home/michael/Documents/Projects/migadu_mail/haraka-outgoing/node_modules/Haraka/mailheader.js:52:28
```

### Steps to reproduce

Try to send the following email:

[testemail.txt](https://github.com/haraka/Haraka/files/471799/testemail.txt)

using, for instance, 

    swaks -f aaa@bbb.com -t aaa@bbb.com -s localhost -no-data-fixup -p 2525 -d testemail.txt

### PR DESCRIPTION
**Pull request by baudehlo**
Fixes #1596 .

Changes proposed in this pull request:
- Catch errors from decodeURIcomponent()

Checklist:
- [ ] docs updated
- [ ] tests updated

### CODE REVIEW

File: mailheader.js [hunk 1]
```diff
@@ -135,7 +135,12 @@ function _decode_rfc2231 (params) {
 
         params.cur_key = key_actual;
         params.keys[key_actual] = '';
-        value = decodeURIComponent(value);
+        try {
+            value = decodeURIComponent(value);
+        }
+        catch (e) {
+            logger.logerror("Decode header failed: " + key + ": " + value);
```
Comment (msimerson) [inline mailheader.js]: Would logging the actual error be good?

**Comment by baudehlo** [comment]
Seemed pretty useless from the ticket, but sure why not.

File: mailheader.js (hunk 1 above)
Comment (baudehlo) [inline mailheader.js]: I get the feeling it won't help much. Knowing the actual key/value is more beneficial.
