### PR TITLE
Set graceful shutdown off by default

### LINKED ISSUE #1926: cluster shutdown/restart issues
### Background

We recently upgraded from haraka 2.7.something to 2.8.13.  We use clustering with 20 workers per instance.  After the upgrade, I noticed that haraka would now take ~20 minutes to shut down after it received a SIGTERM, when it used to happen instantaneously.  This was after spending some time fixing our plugins to properly shutdown when requested, which I initially assumed was causing the issue.

### Problem

I traced the problem back to open connections from clients sending us mail (or not, but leaving the connection open anyway).  Haraka doesn't appear to track client connections anywhere explicitly after they're created, but of course open connections prevent the node main loop from exiting, even after everything else in each worker has been properly closed *and* worker.disconnect() has been called.  This is exacerbated by the way workers are shut down [in serial](https://github.com/haraka/Haraka/blob/f42e75849bcb99b8dce9893baa17541e9db07bc7/server.js#L135) and waited on ([up to 1 minute](https://github.com/haraka/Haraka/blob/f42e75849bcb99b8dce9893baa17541e9db07bc7/server.js#L129)) to fully exit.  For deployments of sufficient volume (where you're almost guaranteed at least a few client connections will hold the line without doing anything) using clustering, this means that shutting down haraka now takes as many minutes as there are workers.

### Steps to Reproduce

* Set your smtp.ini with `nodes=2` or more.
* Run haraka, e.g. from master: `node haraka.js`.
* Open a few connections to haraka, e.g. `telnet localhost 25`.
* Leave those connections open and untouched, and send `SIGTERM` to the master process, e.g. `kill ...`.
* Observe that haraka starts to shut down immediately, but stays up, and the connections stay active.
* After one minute, whatever connections that hit the first haraka worker will get closed and haraka will move on to the second worker, etc.
* The whole process only goes down after as many minutes as you had workers with open connections.

I'd expect it to go down in a fixed, even if somewhat long, amount of time.  It's not a huge issue, but I'd expect anyone running the latest version at scale to see the same thing, and it makes scaling slightly more painful.

### Potential Fixes

I'm guessing it's a feature that connections are allowed time to wrap up and close on their own.  I'd love to see the connections being tracked (bonus points for actually keeping tabs on what part of the conversation they're in and waiting until the transaction isn't in a state where dropping the connection might lead to data loss, e.g. after `data_post` but before it's been confirmed from the `smtp_forward` host) and closed after some shorter timeout than the workers themselves get, especially if inactive.

I think there's a quick solution here that gets us part of the way there without changing too much code:  how would people feel about changing the worker shutdown logic to use `async.eachLimit()` instead of [`async.eachSeries()`](https://github.com/haraka/Haraka/blob/f42e75849bcb99b8dce9893baa17541e9db07bc7/server.js#L135), with a limit of `nodes / 2`.  That way there are still always nodes up listening for connections, as is needed if you're doing a graceful restart, but the total time is always capped at a fixed value, instead of growing with the number of nodes.

If that seems like a good idea, I'd be happy to whip up a patch (I'd also take a stab at getting those worker timeouts to be configurable).

All of this was tested on master, node v4.2.6, linux 4.4.0-72-generic x86_64 (ubuntu 16.04).

### Bonus Problem

It doesn't appear that the graceful restart option actually works if you have cluster enabled.  If you use the bin to do `--graceful`, it properly connects to a node and goes through the `INTERNALCMD` rigamarole, even [sending the master process the right message](https://github.com/haraka/Haraka/blob/f42e75849bcb99b8dce9893baa17541e9db07bc7/server.js#L208).  The master process doesn't seem to be listening for that message anywhere though, so it never does the restart.

I'd be happy to include this in my patch, providing someone can give me security guidance on it (i.e. the `INTERNALCMD` mechanism is required to come from localhost *and* have the secret key, and I'm guessing node implements this IPC mechanism as a pipe, but if it's a named pipe or socket of some kind it should get the same treatment I assume).

Also happy to break this out into a separate issue either way.

### PR DESCRIPTION
**Pull request by baudehlo**
Fixes #1926

Changes proposed in this pull request:
- Still allow haraka -c <path> --graceful
- Also sets graceful shutdown to shutdown in max 2xChildren amount of time it sets to shutdown.
- Shutdown gracefully now requires smtp.ini to contain `graceful_shutdown=true`.

Checklist:
- [ ] docs updated
- [ ] tests updated

### CODE REVIEW

**Comment by msimerson** [comment]
Hrmm, the nodemailer integration test is failing with this change. Not sure why.

**Comment by baudehlo** [comment]
Fixed that issue and made it a bit more sane.

File: configfile.js [hunk 1]
```diff
@@ -266,6 +266,7 @@ cfreader.ensure_enoent_timer = function () {
             })(files[i]); // END BLOCK SCOPE
         }
     }, 60 * 1000);
+    cfreader._enoent_timer.unref();
```
Comment (baudehlo) [inline configfile.js]: BTW how come we now have a haraka-config package and this file is still in Haraka?

File: server.js [hunk 2]
```diff
@@ -1,6 +1,7 @@
 'use strict';
 // smtp network server
 
+// var log = require('why-is-node-running');
```
Comment (baudehlo) [inline server.js]: BTW I left this in but commented because it makes it easy to debug any kind of "won't quit" issues in the future.

File: tls_socket.js [hunk 3]
```diff
@@ -137,6 +137,10 @@ pluggableStream.prototype.setKeepAlive = function (bool) {
 pluggableStream.prototype.setNoDelay = function (/* true||false */) {
 };
 
+pluggableStream.prototype.unref = function () {
+    return this.targetsocket.unref();
+};
```
Comment (baudehlo) [inline tls_socket.js]: I added this in case we need to unref a socket in the future.

File: configfile.js (hunk 1 above)
Comment (msimerson) [inline configfile.js]: Since moving config into a module (so npm plugins could depend on it) I've been moving more and more stuff to depend on haraka-config, with the eventual plan to deprecate the build-in conifg.js and configfile.js. We're a ways down that road and I don't recall right now what's left to do.

File: server.js (hunk 2 above)
Comment (msimerson) [inline server.js]: Says the guy that use to be adamantly opposed to such a thing. ;-)  Welcome to the dark side. ;-)

File: tls_socket.js (hunk 3 above)
Comment (msimerson) [inline tls_socket.js]: Could this ever get called while targetsocket is undefined?

**Comment by baudehlo** [comment]
No we never undef the targetsocket. Everything else would break too if we did.
